### ISSUE TITLE
NAN convert 

### ISSUE THREAD

**Issue by ShangGaoG** [xiaozai/DeT#6]
depthtrack.py
gt = pandas.read_csv(bb_anno_file, delimiter=',', header=None, dtype=np.float32, na_filter=False, low_memory=False).values
maybe na_filter should be true?

**Comment by xiaozai** [comment]
I think that it comes from **ltr.dataset.depthtrack.py**,  it does not matter, because the training process uses only **target_visible** frames, please check **_read_target_visible(self, seq_path)**, if gt is nan, it means the frame belongs to out_of_view or full_occlusion.

And you can set the bbox size in **get_sequence_info(self, seq_id)**, in our work, we ignore the bbox < 10 pixels, but in the original pytracking, they ignore the bbox < 0. 

And ofc you can edit it to True, it is also okay.
